### ISSUE TITLE
No virtual method setEndpointIdentificationAlgorithm

### ISSUE THREAD

**Issue by Hospes** [aws/aws-iot-device-sdk-java#18]
Hello guys. I found one problem.

Lib crashed if it used on Android API less than 24.

Calling this constructor:
```
    public AWSIotMqttClient(String clientEndpoint, String clientId, KeyStore keyStore, String keyPassword) {
        super(clientEndpoint, clientId, keyStore, keyPassword);
    }
```
Will cause following exception:
```
java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)
                      at com.amazonaws.services.iot.client.util.AwsIotTlsSocketFactory.ensureTls(AwsIotTlsSocketFactory.java:124)
                      at com.amazonaws.services.iot.client.util.AwsIotTlsSocketFactory.createSocket(AwsIotTlsSocketFactory.java:80)
                      at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:69)
                      at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
                      at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
                      at java.lang.Thread.run(Thread.java:818)
```

if you will look into the `AwsIotTlsSocketFactory#ensureTls` method, you'll see next code:
```
    private Socket ensureTls(Socket socket) {
        if (socket != null && (socket instanceof SSLSocket)) {
            ((SSLSocket) socket).setEnabledProtocols(new String[] { TLS_V_1_2 });

            // Ensure hostname is validated againt the CN in the certificate
            SSLParameters sslParams = new SSLParameters();
            sslParams.setEndpointIdentificationAlgorithm("HTTPS");
            ((SSLSocket) socket).setSSLParameters(sslParams);
        }
        return socket;
    }
```

So lib crashed in line: `sslParams.setEndpointIdentificationAlgorithm("HTTPS");` if app was launched on android api less than 24.
Here is official docs: [SSLParameters#setEndpointIdentificationAlgorithm(java.lang.String)](https://developer.android.com/reference/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm(java.lang.String))
[Direct link to file in repo](https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/util/AwsIotTlsSocketFactory.java)

**Comment by fengsongAWS** [comment]
Hi @Hospes ,

Thanks for your feed back on AWS IoT Java SDK. Currently the IoT Java SDK has not been fully tested running on Android. If you are interested in connecting to IoT using Android mobile, you may find useful samples under this repository: https://github.com/awslabs/aws-sdk-android-samples

However, we are making efforts to merge AWS IoT Java SDK to be Android compatible and I think this information is very important.

Thanks for your interest in AWS IoT SDK.

**Comment by Hospes** [comment]
Hi everyone again!
I made fork of this repo and do some fixes for using this library on Android.
Here is link to repo: [aws-iot-device-sdk-android](https://github.com/Hospes/aws-iot-device-sdk-android)
Also I published it to my public maven on bintray: [ ![Download](https://api.bintray.com/packages/hospes/maven/ua.hospes.aws%3Aaws-iot-device-sdk-android/images/download.svg) ](https://bintray.com/hospes/maven/ua.hospes.aws%3Aaws-iot-device-sdk-android/_latestVersion)

Feel free to use it!
@fengsongAWS, also if I did something wrong or violate some license rules just tell me.
Thanks for this sdk!

**Comment by SanyasiraoM** [comment]
@Hospes I'm still getting the same error and you kept min sdk version as 19. Can we make it to 16?

**Comment by SanyasiraoM** [comment]
@Hospes https://github.com/aws/aws-iot-device-sdk-java/issues/28 Any comment on this?

**Comment by Ivan-Busani** [comment]
> Hi everyone again!
> I made fork of this repo and do some fixes for using this library on Android.
> Here is link to repo: [aws-iot-device-sdk-android](https://github.com/Hospes/aws-iot-device-sdk-android)
> Also I published it to my public maven on bintray: [ ![Download](https://camo.githubusercontent.com/66da92e9d63e5c16fcacbe8fc1bc77cee4b2edd2/68747470733a2f2f6170692e62696e747261792e636f6d2f7061636b616765732f686f737065732f6d6176656e2f75612e686f737065732e6177732533416177732d696f742d6465766963652d73646b2d616e64726f69642f696d616765732f646f776e6c6f61642e737667) ](https://bintray.com/hospes/maven/ua.hospes.aws%3Aaws-iot-device-sdk-android/_latestVersion)
> 
> Feel free to use it!
> @fengsongAWS, also if I did something wrong or violate some license rules tell me, please.
> Thanks for this sdk!

You saved my life... Thank you!!

**Comment by Ivan-Busani** [comment]
@Hospes you saved my life... Thank you!!
